language: node_js
node_js:
  - '0.10'
install:
  - cd skylark
  - npm install -g testem
  - npm install -g test/sauce
  - npm install
before_script:
  - grunt dist
  - grunt compile:test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - testem ci -l Firefox
env:
  global:
    - secure: "eCp3k36c1uFw8wtcqKvqfU6cjSHczOX64kcJHG0Huc8Hw6PsCt6C1LQwHVsSpDNZhdfHewQrjNku+pufmiw9peim3YN2JLlJIGRshgUHW3t2BiJZt8RapfJj6gxAfc6H/9Zhe3RrKssqtsVakExNwrQSNOb42jvCJ/biqonku/Y="
    - secure: "SibQJyZbHFkodDSRoUkqUcM/iAJxwKxCO8OfL+UNPg56BzFYofO3nJMAeuRmX9xCedyDEK9+XevtCf2IFwzrCLAUdBi4aFG9CQVqIICnAnFnf6UWcjeC6v7LzUY3hWwrBlU6i1F7GzeI+gT2dF9qEJRgQayxChSI2286xtoJahQ="
